#ifndef Demo_codeObfuscation_h
#define Demo_codeObfuscation_h
//confuse string at date
#define HHJ_GetAllAppBundleID IYKfzwvysBRilJad
#define touss xqiibvrmILvFwGPD
#define allInstalledBundleID NkMBgKRfafBweWDx
#define openApplicationWithBundleID gWmUJZjGCYPxGrQk
#define ls_hhj_Application_hhj_Workspace_hhj_Function dMnPWJcDOqtlvdEs
#define default_hhj_Workspace_hhj_Function tmPtBaRYTLfoekws
#define all_hhj_Installed_hhj_Applications_hhj_Function SKnnaVjCBAXObiRK
#define open_hhj_Application_hhj_With_hhj_Bundle_hhj_ID_hhj_Function ESdYmEJCAceBNHbb
#endif
